[package]
name = "bea_game_hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
rand = "0.8.5"

[build-dependencies]
cc = "1.0"

[profile.dev.package."*"]
opt-level = 3
