name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildWASM:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update local toolchain
      run: |
        rustup update
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings    
    - name: installs
      run: |
        rustup target install wasm32-unknown-unknown
        cargo install -f wasm-bindgen-cli
    - name: build
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --out-dir ./web/ --target web ./target/wasm32-unknown-unknown/release/bea_game_hub.wasm
    - name: serve
        
    
    
    
    
        